#!/usr/bin/env python

import os
import sys

def setup_moby(moby_file):
    moby = {}

    with open(moby_file, 'r') as f:
        text = f.read()

    for line in text.split('\n'):
        word = line.strip()
        moby[word.replace('\xa5','')] = word.split('\xa5')

    return moby

def insert_word(word, hyph, moby):
    with open('mhyph.txt', 'r') as f:
        text = f.read()
    lines = text.split('\n')
    lower = 0
    upper = len(lines)

    while len(lines[lower:upper]) > 1:
        i = ((upper - lower) // 2) + lower
        if word.lower() > lines[i].replace('\xa5','').lower().strip():
            lower = i
        else:
            upper = i

    lines.insert(i + 1, hyph)

    print("Word replaced in moby. Regenerating list...\n")

    with open('mhyph2.txt', 'w') as f:
        f.write('\n'.join(lines))

    os.rename('mhyph2.txt', 'mhyph.txt')

def main(argv):
    if len(argv) < 3:
        print("USAGE: add_word.py NEW_WORD HYPHENATED_WORD")
        print("Example: add_word.py hyphenated hy-phe-na-ted\n")
        print("Remember to keep the hyphenated word together.\n")
        sys.exit(1)

    word = sys.argv[1].strip()
    hyph = sys.argv[2].strip().replace('-','\xa5')

    moby = setup_moby('mhyph.txt')

    if (word not in moby) or (word.lower() not in moby):
        insert_word(word, hyph, moby)
    else:
        if word in moby:
            print("Word \"%s\" was found in moby as %s.\n" % (word, moby[word]))
        elif word.lower() in moby:
            print("Word \"%s\" was found in moby as %s.\n" % (word, moby[word.lower()]))
        if sys.version_info >= (3,0):
            r = input("Replace existing word? (y/n) ")
        else:
            r = raw_input("Replace existing word? (y/n) ")

        if r == 'y':
            insert_word(word, hyph, moby)

if __name__ == "__main__":
    main(sys.argv)
