"""Initial.

Revision ID: 57dc72c57001
Revises: 
Create Date: 2021-10-22 10:45:26.591584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57dc72c57001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beatleboard_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gtr_id", sa.Integer(), nullable=True),
        sa.Column("gtr_username", sa.Text(), nullable=True),
        sa.Column("drums_id", sa.Integer(), nullable=True),
        sa.Column("drums_username", sa.Text(), nullable=True),
        sa.Column("bass_id", sa.Integer(), nullable=True),
        sa.Column("bass_username", sa.Text(), nullable=True),
        sa.Column("vox_id", sa.Integer(), nullable=True),
        sa.Column("vox_username", sa.Text(), nullable=True),
        sa.Column("harms_id", sa.Integer(), nullable=True),
        sa.Column("harms_username", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("image_proof", sa.Text(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("uploader_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beatleboard_songs",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("album", sa.Text(), nullable=False),
        sa.Column("artist", sa.Text(), nullable=False),
        sa.Column("released", sa.DateTime(), nullable=False),
        sa.Column("visible", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "beatleboard_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("userid", sa.Text(), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("beatleboard_users")
    op.drop_table("beatleboard_songs")
    op.drop_table("beatleboard_scores")
    # ### end Alembic commands ###
